/**
 * Itmes
 */

export const product = [
  {
    id: 1,
    title: "Tenis Blanco",
    category: "hombre",
    price: 280,
    img: "./img/image-1.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 2,
    title: "Tenis Puma",
    category: "hombre",
    price: 250,
    img: "./img/image-2.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 3,
    title: "Tenis Pirma",
    category: "mujer",
    price: 300,
    img: "./img/image-3.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 4,
    title: "Botas",
    category: "hombre",
    price: 350,
    img: "./img/image-4.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 5,
    title: "Tenis Urban",
    category: "niños",
    price: 380,
    img: "./img/image-5.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 6,
    title: "Tenis Urban II",
    category: "niños",
    price: 300,
    img: "./img/image-6.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 7,
    title: "Tenis Black",
    category: "mujer",
    price: 350,
    img: "./img/image-7.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 8,
    title: "Tenis Black",
    category: "hombre",
    price: 300,
    img: "./img/image-8.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 9,
    title: "Tenis Black Plataform",
    category: "mujer",
    price: 350,
    img: "./img/image-9.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 10,
    title: "Tenis Unicornio",
    category: "mujer",
    price: 300,
    img: "./img/image-10.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 11,
    title: "Tenis Arcoiris",
    category: "mujer",
    price: 300,
    img: "./img/image-11.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
  {
    id: 12,
    title: "Tenis Vans",
    category: "niños",
    price: 280,
    img: "./img/image-12.jpeg",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
  },
];
